input_mode: fastq_copy  # options: sra | bam | fastq_copy or fastq_link (
samples_sra: metadata/samples_sra.csv
samples_bam: metadata/samples_bam.csv
samples_fastq: metadata/samples_fastq.csv

# directories dont need to exist before running pipeline publishdir makes them

fastq_data: /scratch/home/agupta1/pipelinetest/fq_data 
results: /scratch/home/agupta1/pipelinetest/res_data