input_mode: sra  # options: sra | bam | 
samples_sra: metadata/samples_sra.csv
samples_bam: metadata/samples_bam.csv
samples_fastq: metadata/samples_fastq.csv

# directories dont need to exist before running pipeline publishdir makes them

fastq_data: /scratch/home/agupta1/coup/data/pipelinetest1/fq_data
results: /scratch/home/agupta1/coup/data/pipelinetest1/res_data