---
title: "05_Cell_Annotation_Cont"
author: "Ananya Gupta"
date: "2025-11-12"
output: html_document
---
```{r}
install.packages('metap')
```
```{r}
BiocManager::install('multtest')
```


```{r env_loading, results='FALSE',}
# Load packages, data and functions
library(Seurat)
library(SeuratWrappers)
library(magicBatch)
library(BPCells)
library(batchelor)
library(patchwork)
library(Azimuth)
library(plotly)
library(hdf5r)
library(kableExtra)
library(ggplot2)
library(gridExtra)
library(DT)
library(clustree)
library(Matrix)
library(scales)
library(data.table)
library(dplyr)
library(ggrepel)
library(gprofiler2)
library(multtest)
library(metap)
# Set the random number seed
set.seed(1234)
```

Cell Annotation

```{r}
# Load it back
seu <- readRDS("seu_bec_clean_post_umap.rds")
```



```{r,fig.width=10,fig.height=4}
DimPlot(seu, reduction = 'umap.bec', group.by = 'mnn.clusters.bec', label = TRUE)|DimPlot(seu, reduction = 'umap.bec', group.by = 'genotype') #+ ggtitle("Blood Endothelial Cells Clustered, Batch Effect Removed")

#condition|clusters
```
Before we start our marker identification we will explicitly set our default assay, we want to use the normalized data, but not the integrated data.
```{r}
DefaultAssay(seu) <- "RNA"
Idents(seu) <- "mnn.clusters.bec"
```

Afetr changing to RNA



```{r,fig.width=10,fig.height=4}
DimPlot(seu, group.by = 'mnn.clusters.bec', label = TRUE)|DimPlot(seu,  group.by = 'genotype') #+ ggtitle("Blood Endothelial Cells Clustered, Batch Effect Removed")

#condition|clusters
```

```{r}
art_mark <- c("Sox17", "Bmx","Gja5") #did not find Gkn3
pre_art <- c("Sox17", "Gja4", "Depp1")
PCV <- c("Selp")
```


```{r}
Seurat::FeaturePlot(seu, art_mark, ncol=2)#,min.cutoff = 'q10')
```
```{r}

levels(Idents(seu))
clusters <- levels(Idents(seu))
```

```{r}
conserved_list <- lapply(clusters, function(cl){
  FindConservedMarkers(
    seu,
    ident.1 = cl,
    only.pos = TRUE,
    grouping.var = "genotype",
    assay = "RNA",
    slot = "data"
  )
})
names(conserved_list) <- clusters
```

