---
title: "genes-from-ensembl"
author: "Ananya Gupta"
date: "2025-11-13"
output: html_document
---
https://hbctraining.github.io/Intro-to-scRNAseq/lessons/fetching_annotations.html

```{r}
library(AnnotationHub)
library(ensembldb)
library(dplyr)

```


```{r}
# Connect to AnnotationHub
ah <- AnnotationHub()

# Access the Ensembl database for organism
ahDb <- query(ah, 
              pattern = c("Mus musculus", "EnsDb"), 
              ignore.case = TRUE)

# Acquire the latest annotation files
id <- ahDb %>%
        mcols() %>%
        rownames() %>%
        tail(n = 1)

# Download the appropriate Ensembldb database
edb <- ah[[id]]

# Extract gene-level information from database
annotations <- genes(edb, 
                     return.type = "data.frame")

# Select annotations of interest
annotations <- annotations %>%
        dplyr::select(gene_id, gene_name, seq_name, gene_biotype, description)

```


```{r}
head(annotations)
```

```{r}
write.csv(annotations, "mouse_annotations.csv", row.names = FALSE)

```















